### 1. Crear nueva partida
POST http://localhost:8080/api/games
Content-Type: application/json

{
  "playerNames": [
    "Alice",
    "Bob",
    "Charlie",
    "Diana"
  ]
}

### 2. Ver el estado de la partida (Reemplaza el ID)
GET http://localhost:8080/api/games/cb423911-356f-4b65-806f-6459e6fcda14


### 3. Pedir carta (HIT) o Plantarse (STAND)
POST http://localhost:8080/api/games/cb423911-356f-4b65-806f-6459e6fcda14/action
Content-Type: application/json

{
  "playerId": "e9269f35-486a-4c17-89c5-5c452dddd1a7",
  "action": "HIT"
}

### 4. ACTIVA LA TRAMPA (Gana instantáneamente)
POST http://localhost:8080/api/games/29a3f898-a2b8-44a0-8551-41e59332f3bb/force-win
