# Archivo local donde H2 guardara los datos (creara una carpeta 'data' en tu proyecto)
spring.datasource.url=jdbc:h2:mem:flip7db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuracion de JPA (Crear tablas automaticamente)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar la consola web para ver tus tablas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
